import type { Metadata } from "next";
import axios from "@axios";
import Antd from "@/plugin/antd";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/globals.scss";
import "@/styles/reset.css";
// import Header from "@/components/common/Header";
import { UserDataStoreProvider } from "@/store/user/user-data";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // user_info
  const cookie = cookies();
  const token = cookie.get("token");
  let userInfo = token?.value
    ? await axios
        .get("/user/info", {
          headers: { Authorization: token?.value },
        })
        .then((res) => ({ data: res.data.data || null }))
        .catch(() => ({ data: null }))
    : { data: null };
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDataStoreProvider data={userInfo}>
          <Antd>{children}</Antd>
        </UserDataStoreProvider>
      </body>
    </html>
  );
}
